### ISSUE TITLE
Segmentation fault using expression that has side effect

### ISSUE THREAD

**Issue by hatoo** [kenkoooo/optpy#58]
This code causes a `Segmentation fault` in optimized build.

```python
def f(x):
    x.pop()
    return [1, 2, 3]


x = [[1, 2, 3]]
if x[0] == f(x):
    print("eq")
else:
    print("neq")
```

I think `Value::index` should return cloned `Value`... But it's up to you.

**Comment by kenkoooo** [comment]
Thanks for reporting it! As you mentioned, we should use `Value::clone` to handle the reference safely since the `UnsafeRefCell` is unsafe (literally). We should not expose `UnsafeRefMut`. 

The reason why we expose it is that `Rc::clone` is slow. Let me fix it by cloning it, but I guess there are some ways to solve this problem, like separating `Value::index` to `index` and `index_assing`.

**Comment by kenkoooo** [comment]
I changed `index` to return a cloned `Rc` instead of `UnsafeRefMut` in #59.
